# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160831_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.CharField(default='protostart_logo_website-min.png', max_length=100),
        ),
    ]
