# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_event_eventbrite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='facebook_link',
            field=models.CharField(blank=True, help_text='Den gesamten Facebook Link, über den Besucher auf das Event kommen hier einfügen', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='cooperation_partners',
            field=models.TextField(blank=True, help_text='Für eventuelle Partner wie die mitorganisierende Hochschule'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Dieser Text wird in der Übersicht aller Events eventuell abgeschnitten präsentiert und nur auf der Detailansicht vollständig angezeigt. Die wichtigsten Fakten also am Anfang'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventbrite_link',
            field=models.CharField(blank=True, help_text='Den gesamten Eventbrite Link, über den Besucher auf das Event kommen hier einfügen', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Bitte in dem Format: NameDesVeranstaltungsortes, Straße, Stadt', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.CharField(default='protostart_logo_website-min.png', help_text='Den Dateinamen des zu verwendenen Bildes, mit Endung wie .jpg hier einfügen und das Bild dann mit Angabe der betreffenden Veranstaltung an Yannis senden', max_length=100),
        ),
    ]
