# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160907_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Bitte in dem Format: NameDesVeranstaltungsortes, Straße, Stadt, Beispiel: Protostart Firmenzentrale, Hausdorffstraße 34, Bonn', max_length=100),
        ),
    ]
