# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20160907_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='WICHTIG! Hier zumindest einen Schätzwert angeben. Genaue Uhrzeit und Datum werden eh nirgendwo angezeigt, aber Events die ein falsches Enddatum haben werden eventuell in einer falschen kategorie , z.B. Vergangene und nicht zukünftige Events angezeigt'),
        ),
    ]
