# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20160907_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Dieser Text wird in der Übersicht aller Events eventuell abgeschnitten (Die ersten 100 Wörter) präsentiert und nur auf der Detailansicht vollständig angezeigt. Die wichtigsten Fakten also am Anfang'),
        ),
    ]
