# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20160907_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='header',
            field=models.CharField(blank=True, help_text='Dieses Bild wird in der Event Detailansicht als Titelbild (Wie das Titelbild bei Eventbrite) verwendet. Den Dateinamen des zu verwendenen Bildes, mit Endung wie .jpg hier einfügen und das Bild dann mit Angabe der betreffenden Veranstaltung an Yannis senden', max_length=100),
        ),
    ]
